"""
_gen_day8.py — Day 8 Study Material Generator
Creates:
  Day8/lc-0104-max-depth.ipynb
  Day8/lc-0102-level-order.ipynb
  Day8/lc-0226-invert-tree.ipynb
  Day8/lc-0199-right-side-view.ipynb
  Day8/python-pytest.ipynb
  Day8/sql-case-when-pivot.ipynb
  Day8/airflow-orchestration.ipynb
HTML files are generated by running _gen_html.py after this script.
"""
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

BASE = 'D:/Workspace/StudyMaterial/Day8'
os.makedirs(BASE, exist_ok=True)

# ─── Notebook helpers ─────────────────────────────────────────────────────────

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11.0"}
        },
        "cells": cells
    }

def md(cid, text):
    lines = text.split('\n')
    src = [l + '\n' for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])
    return {"cell_type": "markdown", "id": cid, "metadata": {}, "source": src}

def code(cid, text):
    lines = text.split('\n')
    src = [l + '\n' for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])
    return {"cell_type": "code", "id": cid, "metadata": {}, "outputs": [], "execution_count": None, "source": src}

def write_nb(path, cells):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(nb(cells), f, indent=1, ensure_ascii=False)
    print(f'  Written: {path}')


# ─── Shared TreeNode setup code ───────────────────────────────────────────────

TREENODE_CODE = '''\
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

def build_tree(vals):
    """Build tree from level-order list (None = missing node)."""
    if not vals or vals[0] is None:
        return None
    from collections import deque
    root = TreeNode(vals[0])
    q = deque([root])
    i = 1
    while q and i < len(vals):
        node = q.popleft()
        if i < len(vals) and vals[i] is not None:
            node.left = TreeNode(vals[i])
            q.append(node.left)
        i += 1
        if i < len(vals) and vals[i] is not None:
            node.right = TreeNode(vals[i])
            q.append(node.right)
        i += 1
    return root

print("TreeNode ready.")
'''

# ─────────────────────────────────────────────────────────────────────────────
# LC #104 — Maximum Depth of Binary Tree [Easy]
# ─────────────────────────────────────────────────────────────────────────────

LC104_CELLS = [

md('cell-title', '''\
## 🌳 LeetCode 104: Maximum Depth of Binary Tree
---

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #e8f5e9; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> Depth is recursive by nature. The depth of a tree is 1 (the root)
    plus the depth of its deeper subtree. The base case: an empty node has depth 0.
    DFS recursive solves this in 3 lines.
</div>

### 📋 Problem

Given the root of a binary tree, return its **maximum depth** — the number of nodes along
the longest path from the root down to the farthest leaf node.

```
    3          maxDepth = 3
   / \\
  9  20        (path: 3 → 20 → 15 or 3 → 20 → 7)
    /  \\
   15   7
```

**Constraints:** 0 ≤ nodes ≤ 10⁴ | -100 ≤ Node.val ≤ 100
'''),

md('cell-mental-models', '''\
### 🧠 Choose Your Mental Model

| Model | The "Story" | Mechanism |
|-------|-------------|-----------|
| **Russian Dolls** | "I'm a doll. My depth is 1 + the depth of my bigger half." Each call returns depth for its subtree, plus 1. | Recursive: `1 + max(left, right)` |
| **DFS Floor Counter** | "I'm exploring a cave. I count steps as I go down. At every dead-end (leaf), I report how deep I am." | Count levels on the way back up |
| **BFS Level Counter** | "I process the tree floor by floor. Each time I clear a floor, I increment the floor counter." | Queue + level snapshot |
'''),

code('cell-brute-code', '''\
''' + TREENODE_CODE + '''
def maxDepth_brute(root: TreeNode) -> int:
    """
    Brute force: collect ALL root-to-leaf paths, return length of longest.
    Time: O(n)  |  Space: O(n * h) — stores every path
    Pedagogically clear but wastes memory: each leaf stores full path.
    """
    if not root:
        return 0

    paths = []

    def dfs(node, path):
        if not node:
            return
        path.append(node.val)
        if not node.left and not node.right:   # leaf
            paths.append(list(path))            # copy path (don't store reference)
        dfs(node.left,  path)
        dfs(node.right, path)
        path.pop()                              # backtrack

    dfs(root, [])
    return max(len(p) for p in paths) if paths else 0


# Test
root = build_tree([3, 9, 20, None, None, 15, 7])
print("Brute force:", maxDepth_brute(root))   # Expected: 3

root2 = build_tree([1, None, 2])
print("Brute force:", maxDepth_brute(root2))  # Expected: 2
'''),

md('cell-complexity', '''\
## 🔬 Complexity Analysis: Brute Force vs Optimal

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> Both approaches are O(n) time — we must visit every node.
    The difference is space: brute force stores all paths (O(n × h)), while optimal DFS
    only stores the call stack (O(h)), and BFS stores at most one level (O(w)).
</div>

---

## 📉 Why Brute Force Uses More Space

Collecting all root-to-leaf paths:
- A balanced tree of depth h has ~n/2 leaves
- Each path has length h
- Total space: O(n × h) = O(n log n) for balanced, O(n²) for skewed

| Approach | Time | Space | Notes |
|----------|------|-------|-------|
| Brute force (collect paths) | O(n) | O(n × h) | Stores every path |
| **DFS Recursive (optimal)** | **O(n)** | **O(h)** | Call stack only |
| BFS Iterative | O(n) | O(w) | w = max level width |

### Skewed tree space comparison
- Brute force: O(n²) — each of n leaves has a path of length n
- DFS: O(n) — call stack grows to depth n
- BFS: O(1) — only 1 node per level → queue never exceeds size 1

<div style="padding: 10px; border-left: 8px solid #4CAF50; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>✅ Summary:</strong> Use DFS recursive for clean code (O(h) space).
    Prefer BFS iterative when stack overflow is a concern (very deep unbalanced trees).
</div>
'''),

code('cell-optimal-code', '''\
from collections import deque

def maxDepth(root: TreeNode) -> int:
    """
    Optimal DFS Recursive — 3 lines.
    Time: O(n)  |  Space: O(h) — recursion call stack
    h = O(log n) balanced, O(n) worst case (skewed tree)
    """
    if not root:
        return 0
    return 1 + max(maxDepth(root.left), maxDepth(root.right))


def maxDepth_bfs(root: TreeNode) -> int:
    """
    BFS Iterative — counts levels explicitly.
    Time: O(n)  |  Space: O(w) — w = max width of tree
    Preferred when tree may be highly skewed (avoids deep recursion).
    """
    if not root:
        return 0
    queue = deque([root])
    depth = 0

    while queue:
        depth += 1
        for _ in range(len(queue)):      # process entire current level
            node = queue.popleft()
            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)

    return depth


# Tests
root = build_tree([3, 9, 20, None, None, 15, 7])
print("DFS:", maxDepth(root))       # 3
print("BFS:", maxDepth_bfs(root))   # 3

root2 = build_tree([1, None, 2])
print("DFS:", maxDepth(root2))      # 2
print("BFS:", maxDepth_bfs(root2))  # 2

root3 = None
print("DFS empty:", maxDepth(root3))   # 0
'''),

md('cell-qa', '''\
## 🎤 5 Interview Q&A

### Q1: What is the space complexity of the recursive DFS solution?

**Answer:** O(h) where h is the tree height. In the worst case (a completely skewed tree —
every node has only one child), h = n, giving O(n) space. For a balanced binary tree,
h = log n, giving O(log n) space. The space is the call stack — one frame per level of recursion.

---

### Q2: When is BFS preferred over DFS for finding max depth?

**Answer:** When the tree might be highly skewed and you're worried about stack overflow from
deep recursion. Python's default recursion limit is ~1,000. A skewed tree with 10,000 nodes
would cause a RecursionError with DFS. BFS uses an explicit queue and has no recursion limit.
In practice, for balanced trees, DFS is more concise and equally performant.

---

### Q3: Why does `1 + max(left, right)` work? Walk me through the recursion.

**Answer:** For a leaf node: `left = maxDepth(None) = 0`, `right = maxDepth(None) = 0`.
So leaf depth = `1 + max(0, 0) = 1`. ✓
For an internal node: it returns `1 (for itself) + max(depth of left subtree, depth of right subtree)`.
This correctly propagates depth bottom-up. The recursion bottoms out at None → 0.

---

### Q4: What's the difference between height and depth?

**Answer:** Often used interchangeably, but technically:
- **Depth of a node** = distance from root to that node (root has depth 0)
- **Height of a node** = length of longest path from that node to a leaf
- **Height of tree** = height of root = maximum depth of any leaf

LeetCode #104 asks for the height of the root, which equals the maximum depth of any leaf.
The recursive formula `1 + max(left, right)` computes this correctly.

---

### Q5: How would you find the minimum depth of a binary tree?

**Answer:** NOT `1 + min(left, right)` — that's wrong for nodes with only one child
(it would return the depth of the None child = 0, making everything depth 1).
Correct approach: if a node has no left child, recurse only into the right. If no right,
only into left. If both exist, take the min. Or use BFS — the first leaf you encounter
is at minimum depth, so return as soon as you process a leaf.

```python
def minDepth(root):
    if not root: return 0
    if not root.left: return 1 + minDepth(root.right)
    if not root.right: return 1 + minDepth(root.left)
    return 1 + min(minDepth(root.left), minDepth(root.right))
```
'''),

md('cell-citi-narrative', '''\
## 💼 The Citi Narrative

**Context:** Citi's APM infrastructure had a microservices call chain for trade processing.
Each service depended on downstream services — forming a dependency tree rooted at the
trade submission API. Incidents often cascaded down deep call chains.

**The Problem:** "What is the deepest dependency chain in our critical trading path?"
Chains longer than 6 hops were flagged for re-architecture — deep chains increase latency
and make failure isolation harder.

**How Max Depth Applied:** The service dependency graph was a tree (after cycle detection).
The `maxDepth` algorithm ran nightly on the service registry to compute max call chain depth.
Any chain exceeding 6 was reported to the architecture team.

**Practical extension:** Instead of depth, compute the **critical path latency** —
each node had a `p99_latency_ms` attribute. The "depth" became the maximum sum of latencies
along any root-to-leaf path. This is a simple extension: `max_latency(node) = node.p99 + max(left, right)`.

**Interview Line:** *"At Citi, we modeled the microservices call graph as a tree. The max depth
algorithm ran nightly — chains deeper than 6 services were escalated. We later extended it to
sum p99 latencies instead of counting hops, which is just replacing 1 with node.latency in the
recursion. Same algorithm, richer signal."*
'''),

code('cell-practice', '''\
# ── PRACTICE: Diameter of Binary Tree ──────────────────────────────────────
# Given a binary tree, return the length of the DIAMETER —
# the longest path between ANY two nodes (path may not pass through root).
# The diameter at any node = left_depth + right_depth.
# Hint: track max diameter as a side effect during the depth recursion.
#
# Example: [1,2,3,4,5] → diameter = 3 (path: 4-2-1-3 or 5-2-1-3)

def diameterOfBinaryTree(root: TreeNode) -> int:
    # Your solution here
    pass

# Test
root = build_tree([1, 2, 3, 4, 5])
print(diameterOfBinaryTree(root))    # Expected: 3

# Solution:
def diameterOfBinaryTree_sol(root):
    max_diam = [0]
    def depth(node):
        if not node: return 0
        L = depth(node.left)
        R = depth(node.right)
        max_diam[0] = max(max_diam[0], L + R)   # diameter through this node
        return 1 + max(L, R)
    depth(root)
    return max_diam[0]

print("Diameter:", diameterOfBinaryTree_sol(build_tree([1, 2, 3, 4, 5])))   # 3
print("Diameter:", diameterOfBinaryTree_sol(build_tree([1, 2])))             # 1
'''),

md('cell-summary', '''\
## 🎯 Summary: Key Takeaways

### The Pattern
**DFS Recursive:** `maxDepth(root) = 0 if not root else 1 + max(left, right)`

### When to Use Each Approach
- ✅ **DFS Recursive** — clean, 3 lines, default choice for balanced trees
- ✅ **BFS Iterative** — preferred for skewed trees to avoid recursion depth limit
- ❌ **Collect all paths** — O(n × h) space — never in production

### Complexity
| Approach | Time | Space |
|----------|------|-------|
| DFS Recursive | O(n) | O(h) |
| BFS Iterative | O(n) | O(w) |

### Extensions (know these for follow-ups)
- **Minimum depth:** handle single-child nodes explicitly
- **Diameter:** track `left_depth + right_depth` as a side effect
- **Path with max sum:** replace 1 with node.val, handle negatives carefully

### Interview Confidence Checklist
- [ ] Can write DFS solution from memory in 60 seconds
- [ ] Can explain O(h) space complexity with skewed vs balanced example
- [ ] Can write BFS iterative version with level snapshot
- [ ] Can connect to Citi: service dependency chain depth
- [ ] Can extend to diameter (most common follow-up)

**"Simplicity and clarity is Gold."** — Sean's Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/lc-0104-max-depth.ipynb', LC104_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# LC #102 — Binary Tree Level Order Traversal [Medium]
# ─────────────────────────────────────────────────────────────────────────────

LC102_CELLS = [

md('cell-title', '''\
## 🌳 LeetCode 102: Binary Tree Level Order Traversal
---

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #e8f5e9; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> BFS processes nodes level by level naturally.
    The trick: before the inner loop, snapshot <code>level_size = len(queue)</code>.
    This freezes the count for the current level — children added during this level
    are counted separately next iteration.
</div>

### 📋 Problem

Given the root of a binary tree, return its **level-order traversal** as a list of lists —
each inner list contains the values at that depth.

```
Input:  [3, 9, 20, null, null, 15, 7]
Output: [[3], [9, 20], [15, 7]]
```

**Constraints:** 0 ≤ nodes ≤ 2000 | -1000 ≤ Node.val ≤ 1000
'''),

md('cell-mental-models', '''\
### 🧠 Choose Your Mental Model

| Model | The "Story" | Mechanism |
|-------|-------------|-----------|
| **Floor-by-Floor Inspection** | "I inspect a building one floor at a time. Before I start a floor, I count how many doors (nodes) are on it — that count comes from how many doors I added to my list when I finished the floor above." | `level_size = len(queue)` before inner loop |
| **Wave Propagation** | "Dropping a stone in water. Each ripple ring = one level. Process all nodes in the current ring before expanding the next ring." | Queue grows outward, level boundary = `len(queue)` snapshot |
| **DFS + Depth Tag** | "Visit every node, tag it with its depth. Group by depth tag at the end." | Slower O(n log n), but shows the relationship between DFS depth and BFS levels |
'''),

code('cell-brute-code', '''\
''' + TREENODE_CODE + '''
def levelOrder_brute(root: TreeNode) -> list[list[int]]:
    """
    DFS approach: collect (depth, val) pairs, sort by depth, group.
    Time: O(n log n) — dominated by sort  |  Space: O(n)
    Shows that DFS can solve level-order but BFS is the natural fit.
    """
    if not root:
        return []

    pairs = []   # (depth, val)

    def dfs(node, depth):
        if not node:
            return
        pairs.append((depth, node.val))
        dfs(node.left,  depth + 1)
        dfs(node.right, depth + 1)

    dfs(root, 0)
    pairs.sort()   # sort by depth — O(n log n)

    result = []
    i = 0
    while i < len(pairs):
        d = pairs[i][0]
        level = []
        while i < len(pairs) and pairs[i][0] == d:
            level.append(pairs[i][1])
            i += 1
        result.append(level)
    return result


# Test
root = build_tree([3, 9, 20, None, None, 15, 7])
print("Brute force:", levelOrder_brute(root))   # [[3], [9, 20], [15, 7]]
'''),

md('cell-complexity', '''\
## 🔬 Complexity Analysis

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> BFS is O(n) because it processes each node exactly once.
    The DFS approach is O(n log n) because it sorts all (depth, val) pairs — unnecessary extra cost
    when BFS naturally delivers nodes in level order.
</div>

---

## 📊 Why BFS is Natural for Level Order

After sorting by depth (brute force), each node at depth d was already in level-order
within that depth IF we used left-first DFS. But we still pay O(n log n) for the sort.

BFS avoids this: the queue maintains left-to-right order within each level automatically.

| Approach | Time | Space | Order guarantee |
|----------|------|-------|----------------|
| DFS + sort | O(n log n) | O(n) | Sort-dependent |
| **BFS (optimal)** | **O(n)** | **O(n)** | Natural left-to-right |

### The Level Snapshot Trick
```
Queue at start:      [3]
After level 1:       [9, 20]     → level_size was 1, result = [[3]]
After level 2:       [15, 7]     → level_size was 2, result = [[3],[9,20]]
After level 3:       []          → level_size was 2, result = [[3],[9,20],[15,7]]
```

`level_size = len(queue)` freezes the count BEFORE the inner loop adds children.

<div style="padding: 10px; border-left: 8px solid #4CAF50; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>✅ Key Rule:</strong> Snapshot len(queue) before the inner loop.
    This is the entire secret to BFS level separation.
</div>
'''),

code('cell-optimal-code', '''\
from collections import deque

def levelOrder(root: TreeNode) -> list[list[int]]:
    """
    BFS with level snapshot.
    Time: O(n)  |  Space: O(n) — queue holds at most one full level
    The critical line: level_size = len(queue) BEFORE the inner loop.
    """
    if not root:
        return []

    result = []
    queue = deque([root])

    while queue:
        level_size = len(queue)     # ← snapshot: nodes at THIS level
        level = []

        for _ in range(level_size):
            node = queue.popleft()
            level.append(node.val)

            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)

        result.append(level)

    return result


# Tests
root = build_tree([3, 9, 20, None, None, 15, 7])
print("Level order:", levelOrder(root))   # [[3], [9, 20], [15, 7]]

root2 = build_tree([1])
print("Single node:", levelOrder(root2))  # [[1]]

print("Empty:", levelOrder(None))         # []

# Extension: return values in reverse level order (bottom-up)
# Just return result[::-1]
print("Reversed:", levelOrder(root)[::-1])  # [[15, 7], [9, 20], [3]]
'''),

md('cell-qa', '''\
## 🎤 5 Interview Q&A

### Q1: What is the key to separating levels in BFS?

**Answer:** `level_size = len(queue)` — snapshot the queue size BEFORE the inner loop.
This tells you exactly how many nodes belong to the current level.
Children added during this loop are at the next level and get counted in the next iteration.
Without this snapshot, you cannot distinguish where one level ends and the next begins.

---

### Q2: What is the space complexity and what determines it?

**Answer:** O(n) — the queue holds at most one full level at a time.
The widest level of a perfect binary tree of depth h contains n/2 nodes (the leaf level).
So worst-case queue size = O(n/2) = O(n). The result list also takes O(n) total.

---

### Q3: BFS vs DFS for level order — when would you choose DFS?

**Answer:** In languages without a built-in queue (rare). Or when recursion is required
by the problem's API (e.g., a tree visitor pattern). The DFS approach needs depth tracking
and produces O(n log n) due to sorting. In practice: always use BFS for level order.

---

### Q4: How do you modify this to get the RIGHT side view (LC #199)?

**Answer:** Capture only the LAST element of each level:
```python
if i == level_size - 1:
    result.append(node.val)
```
Or keep the existing structure and return `[level[-1] for level in levelOrder(root)]`.

---

### Q5: Real-world use case for level-order traversal?

**Answer:** Many. Tree serialization (the format LeetCode uses is level-order).
Finding the minimum depth (first level with a leaf node).
Printing an org chart or category hierarchy tier by tier.
At Citi: processing all servers in the same network tier together before moving to the next tier.
Any "breadth-first" problem: shortest path in an unweighted graph is BFS.
'''),

md('cell-citi-narrative', '''\
## 💼 The Citi Narrative

**Context:** Citi's server fleet was organized in a hierarchy: Region → DataCenter → Rack → Server.
This formed a tree structure. Monthly capacity reviews processed servers tier-by-tier:
first all regions, then all datacenters within each region, then racks, then individual servers.

**How Level Order Applied:** The capacity review report was essentially a level-order traversal
of the infrastructure tree. Each "level" in the report corresponded to a tier in the hierarchy.
Processing level-by-level enabled parallel workload distribution: all servers at the same tier
could be processed simultaneously (no dependency on each other).

**Practical Extension:** Instead of collecting values, the algorithm collected `(server_id, avg_cpu)`
pairs per tier. If any tier had average CPU above 80%, the review flagged that tier before
drilling into the individual server level.

**SQL Equivalent:** Level-order traversal of hierarchical data in SQL is a **recursive CTE**.
The "level" in BFS corresponds to the depth column in a recursive CTE:
```sql
WITH RECURSIVE hierarchy AS (
    SELECT id, name, parent_id, 0 AS depth FROM infrastructure WHERE parent_id IS NULL
    UNION ALL
    SELECT c.id, c.name, c.parent_id, h.depth + 1
    FROM infrastructure c JOIN hierarchy h ON c.parent_id = h.id
)
SELECT depth, name FROM hierarchy ORDER BY depth, name;
```

**Interview Line:** *"At Citi, the infrastructure hierarchy was a tree. Monthly reviews
processed it level-by-level — all datacenters first, then racks, then servers.
That's exactly level-order traversal. The BFS queue made it natural:
snapshot level size, process that tier, then the next."*
'''),

code('cell-practice', '''\
# ── PRACTICE: Binary Tree Zigzag Level Order Traversal (LC #103) ───────────
# Same as level order, but alternate directions: left→right, then right→left.
# Example: [3,9,20,null,null,15,7] → [[3],[20,9],[15,7]]
#
# Hint: track a boolean `left_to_right`. Each level, flip it.
# Use collections.deque for each level — appendleft when going right-to-left.

from collections import deque

def zigzagLevelOrder(root: TreeNode) -> list[list[int]]:
    # Your solution here
    pass

# Test
root = build_tree([3, 9, 20, None, None, 15, 7])
print(zigzagLevelOrder(root))   # Expected: [[3], [20, 9], [15, 7]]

# Solution:
def zigzagLevelOrder_sol(root):
    if not root:
        return []
    result = []
    queue = deque([root])
    left_to_right = True
    while queue:
        level_size = len(queue)
        level = deque()
        for _ in range(level_size):
            node = queue.popleft()
            if left_to_right:
                level.append(node.val)
            else:
                level.appendleft(node.val)   # prepend = reverse direction
            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)
        result.append(list(level))
        left_to_right = not left_to_right
    return result

print("Zigzag:", zigzagLevelOrder_sol(build_tree([3, 9, 20, None, None, 15, 7])))  # [[3],[20,9],[15,7]]
'''),

md('cell-summary', '''\
## 🎯 Summary: Key Takeaways

### The Pattern
**BFS + Level Snapshot:** `level_size = len(queue)` before the inner loop.

### The One Rule
Process exactly `level_size` nodes in the inner loop. The children they enqueue belong to the NEXT level.

### Common Variants (all use the same skeleton)
| Problem | Change |
|---------|--------|
| Level order (this) | Collect full level |
| Right side view | Take `level[-1]` only |
| Zigzag level order | Alternate append/appendleft |
| Average of levels | `sum(level) / len(level)` |
| Max width | `max(max_w, level_size)` |
| Minimum depth | Stop at first level with a leaf |

### Complexity
| Approach | Time | Space |
|----------|------|-------|
| DFS + sort | O(n log n) | O(n) |
| **BFS (optimal)** | **O(n)** | **O(n)** |

### Interview Confidence Checklist
- [ ] Can write BFS level order from memory in 4 minutes
- [ ] Can explain why `level_size = len(queue)` BEFORE the loop
- [ ] Can name 3 variants that use the same skeleton
- [ ] Can connect to Citi: tier-by-tier infrastructure processing

**"Simplicity and clarity is Gold."** — Sean's Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/lc-0102-level-order.ipynb', LC102_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# LC #226 — Invert Binary Tree [Easy]
# ─────────────────────────────────────────────────────────────────────────────

LC226_CELLS = [

md('cell-title', '''\
## 🌳 LeetCode 226: Invert Binary Tree
---

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #e8f5e9; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> At every node, swap its left and right children.
    Then recursively invert both subtrees. The swap at each node is independent —
    children can be inverted in any order. 4 lines total.
</div>

### 📋 Problem

Mirror a binary tree. Return its root.

```
Input:       Output:
    4            4
   / \\          / \\
  2   7        7   2
 / \\ / \\      / \\ / \\
1  3 6  9    9  6 3  1
```

**Constraints:** 0 ≤ nodes ≤ 100 | -100 ≤ Node.val ≤ 100

> *"Google: 90% of our engineers use the software you wrote (Homebrew),
> but you can't invert a binary tree on a whiteboard so f*** off." — @mxcl (Max Howell, 2015)*
> *This problem became famous because of that tweet.*
'''),

md('cell-mental-models', '''\
### 🧠 Choose Your Mental Model

| Model | The "Story" | Mechanism |
|-------|-------------|-----------|
| **Mirror Flip** | "Place a vertical mirror at the root. Every node's left child becomes its right child and vice versa. This transformation applies at every node simultaneously." | Swap children, recurse both subtrees |
| **DFS Post-Order** | "Visit left, visit right, THEN swap. After both subtrees are inverted, swap the root's children." | Post-order: process children before action at node |
| **DFS Pre-Order** | "Swap first, then visit children. The swap at the root doesn't affect the recursion into children — they get correctly inverted regardless." | Pre-order: swap at node, then recurse |
| **BFS Level-by-Level** | "Go floor by floor. On each floor, swap every node's left and right children." | Queue, swap children on dequeue |
'''),

code('cell-brute-code', '''\
''' + TREENODE_CODE + '''
def invertTree_bfs(root: TreeNode) -> TreeNode:
    """
    BFS iterative — swap children of every node level by level.
    Time: O(n)  |  Space: O(w) — w = max level width
    More explicit, easier to trace for debugging.
    """
    from collections import deque
    if not root:
        return None

    queue = deque([root])

    while queue:
        node = queue.popleft()
        # Swap children
        node.left, node.right = node.right, node.left
        # Enqueue non-null children
        if node.left:  queue.append(node.left)
        if node.right: queue.append(node.right)

    return root


def tree_values(root):
    """Level-order values for testing."""
    if not root: return []
    from collections import deque
    result, q = [], deque([root])
    while q:
        node = q.popleft()
        if node:
            result.append(node.val)
            q.append(node.left)
            q.append(node.right)
        else:
            result.append(None)
    while result and result[-1] is None:
        result.pop()
    return result

root = build_tree([4, 2, 7, 1, 3, 6, 9])
print("Original:", tree_values(root))
inverted = invertTree_bfs(root)
print("BFS inverted:", tree_values(inverted))   # [4, 7, 2, 9, 6, 3, 1]
'''),

md('cell-complexity', '''\
## 🔬 Complexity Analysis

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> Every approach is O(n) time — we must visit every node.
    Space differs: DFS uses call stack O(h), BFS uses queue O(w).
    For this problem, both are equivalent — choose based on style preference.
</div>

---

| Approach | Time | Space | Style |
|----------|------|-------|-------|
| DFS Recursive | O(n) | O(h) | Most concise — 4 lines |
| BFS Iterative | O(n) | O(w) | Explicit, no recursion limit concern |
| DFS Iterative (stack) | O(n) | O(h) | Manual stack, avoids Python recursion |

### Why O(n) is the lower bound
You must visit every node to swap its children.
A node you don't visit won't get its children swapped — producing an incorrect result.
Therefore no algorithm can do better than O(n).

### Space: h vs w
For a balanced binary tree: h ≈ log n, w ≈ n/2 (leaf level).
So DFS (O(log n)) is better than BFS (O(n)) for balanced trees.
For a skewed tree: h = n, w = 1. BFS (O(1)) beats DFS (O(n)).

<div style="padding: 10px; border-left: 8px solid #4CAF50; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>✅ Default choice:</strong> DFS recursive — 4 lines, natural for trees.
    Fallback to BFS if recursion depth is a concern (skewed tree with n > 1000).
</div>
'''),

code('cell-optimal-code', '''\
def invertTree(root: TreeNode) -> TreeNode:
    """
    DFS Recursive — the canonical solution.
    Time: O(n)  |  Space: O(h) — call stack
    4 lines. The swap before recursion is fine because Python evaluates
    the right-hand side first: root.right, root.left = root.left, root.right
    is computed as a tuple swap, then assigned.
    """
    if not root:
        return None

    root.left, root.right = root.right, root.left   # swap

    invertTree(root.left)    # recurse into (previously right) subtree
    invertTree(root.right)   # recurse into (previously left) subtree

    return root


def invertTree_iterative(root: TreeNode) -> TreeNode:
    """
    DFS Iterative using explicit stack — avoids Python recursion limit.
    Time: O(n)  |  Space: O(h)
    """
    if not root:
        return None
    stack = [root]
    while stack:
        node = stack.pop()
        node.left, node.right = node.right, node.left
        if node.left:  stack.append(node.left)
        if node.right: stack.append(node.right)
    return root


# Tests
root = build_tree([4, 2, 7, 1, 3, 6, 9])
inverted = invertTree(build_tree([4, 2, 7, 1, 3, 6, 9]))
print("DFS recursive:", tree_values(inverted))     # [4, 7, 2, 9, 6, 3, 1]

inverted2 = invertTree_iterative(build_tree([4, 2, 7, 1, 3, 6, 9]))
print("DFS iterative:", tree_values(inverted2))    # [4, 7, 2, 9, 6, 3, 1]

# Edge cases
print("Single node:", tree_values(invertTree(build_tree([1]))))    # [1]
print("Two nodes:", tree_values(invertTree(build_tree([1, 2]))))   # [1, None, 2]
'''),

md('cell-qa', '''\
## 🎤 5 Interview Q&A

### Q1: Does the order of the recursive calls matter (left then right vs right then left)?

**Answer:** No. Both calls independently invert their subtrees. When we do `invertTree(root.left)`,
we\'ve already swapped, so `root.left` points to what was previously `root.right`.
Both subtrees get inverted regardless of call order. The result is identical.

---

### Q2: Can you do this iteratively? Walk me through the stack approach.

**Answer:** Yes — use an explicit stack instead of the call stack:
```python
stack = [root]
while stack:
    node = stack.pop()
    node.left, node.right = node.right, node.left
    if node.left:  stack.append(node.left)
    if node.right: stack.append(node.right)
```
This is DFS with an explicit stack. For BFS, use a queue and `popleft()` instead of `pop()`.
Both produce a correctly inverted tree.

---

### Q3: What is the space complexity for a perfectly balanced tree vs a skewed tree?

**Answer:** For DFS recursive, space = O(h) = call stack depth.
- Balanced tree: h = log₂n → O(log n) space
- Skewed tree (all nodes go right): h = n → O(n) space

For BFS: space = O(w) = max queue size = max level width.
- Balanced tree: widest level has n/2 nodes → O(n) space
- Skewed tree: widest level has 1 node → O(1) space

So DFS wins for balanced trees; BFS wins for skewed trees.

---

### Q4: If you invert a tree twice, do you get the original back?

**Answer:** Yes — inverting twice is a self-inverse operation (like XOR with the same value).
`invert(invert(tree)) == original`. Proof: inverting swaps left↔right at every node.
Inverting again swaps right↔left (restoring original). The operation is its own inverse.

---

### Q5: What real-world problem does inverting a tree model?

**Answer:** Mirror transformations in graphics (flip a scene graph left↔right).
Reversing precedence in decision trees (swap which branch is "preferred").
At Citi: inverting a region priority tree — if the primary region fails, we want the
secondary region to take priority, which can be modeled as inverting the tree and
processing it the same way.
'''),

md('cell-citi-narrative', '''\
## 💼 The Citi Narrative

**Context:** Citi\'s monitoring system had a hierarchical alert routing tree:
alerts started at the root (global alert manager) and routed to regions, then datacenters,
then teams. For disaster recovery drills, the team needed to reverse the routing:
instead of routing FROM global TO local, they needed to route FROM local TO global
(escalation testing — see if the escalation path works in reverse).

**How Invert Tree Applied:** The routing tree was inverted so that each node's primary
route became its secondary, and vice versa. This was used in DR mode: local teams
became the decision-makers, escalating up to global only for catastrophic failures.

**The Implementation:** The `invertTree` logic was applied to a Python dataclass tree
representing the alert router configuration. Each `RouterNode` had `primary` and `fallback`
children — inverting the tree made fallbacks primary and vice versa.

**Interview Line:** *"At Citi we ran DR drills where we inverted the alert routing tree —
making the fallback paths primary for testing. It\'s the same algorithm: swap primary and
fallback at every node, recurse. 4 lines of code, tested quarterly."*
'''),

code('cell-practice', '''\
# ── PRACTICE: Symmetric Tree (LC #101) ────────────────────────────────────
# Given a binary tree, check if it is a mirror of itself (symmetric around center).
# Example: [1,2,2,3,4,4,3] → True
# Example: [1,2,2,null,3,null,3] → False
#
# Hint: a tree is symmetric if left subtree is a mirror of right subtree.
# Two trees are mirrors if: their roots are equal AND
#   left.left mirrors right.right AND left.right mirrors right.left.

def isSymmetric(root: TreeNode) -> bool:
    # Your solution here
    pass

# Tests
print(isSymmetric(build_tree([1, 2, 2, 3, 4, 4, 3])))       # True
print(isSymmetric(build_tree([1, 2, 2, None, 3, None, 3])))  # False

# Solution:
def isSymmetric_sol(root):
    def is_mirror(left, right):
        if not left and not right: return True
        if not left or not right:  return False
        return (left.val == right.val
                and is_mirror(left.left, right.right)
                and is_mirror(left.right, right.left))
    return is_mirror(root.left, root.right) if root else True

print("Symmetric:", isSymmetric_sol(build_tree([1, 2, 2, 3, 4, 4, 3])))       # True
print("Symmetric:", isSymmetric_sol(build_tree([1, 2, 2, None, 3, None, 3])))  # False
'''),

md('cell-summary', '''\
## 🎯 Summary: Key Takeaways

### The Pattern
**Swap at every node, recurse into both children.** Pre-order or post-order — both work.

### The 4-Line Solution
```python
def invertTree(root):
    if not root: return None
    root.left, root.right = root.right, root.left
    invertTree(root.left)
    invertTree(root.right)
    return root
```

### Related Problems (same "mirror" insight)
| Problem | Connection |
|---------|------------|
| **Symmetric Tree (101)** | Is the tree a mirror of itself? Use same `is_mirror(left, right)` helper |
| **Same Tree (100)** | Are two trees identical? Same recursive structure |
| **Subtree of Another Tree (572)** | Is tree t a subtree of s? Use "same tree" check at each node |

### Complexity
| Approach | Time | Space |
|----------|------|-------|
| DFS Recursive | O(n) | O(h) |
| BFS Iterative | O(n) | O(w) |

### Interview Confidence Checklist
- [ ] Can write the 4-line DFS solution from memory in 90 seconds
- [ ] Can explain why call order (left before right) doesn\'t matter
- [ ] Can write the BFS iterative version
- [ ] Can extend to Symmetric Tree (same mirror logic, compare two trees)

**"Simplicity and clarity is Gold."** — Sean\'s Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/lc-0226-invert-tree.ipynb', LC226_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# LC #199 — Binary Tree Right Side View [Medium]
# ─────────────────────────────────────────────────────────────────────────────

LC199_CELLS = [

md('cell-title', '''\
## 🌳 LeetCode 199: Binary Tree Right Side View
---

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #e8f5e9; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> Two equivalent approaches:
    (1) BFS — take the LAST node at each level.
    (2) DFS right-first — the FIRST node encountered at each depth is the rightmost.
    BFS is more intuitive. DFS is more space-efficient for balanced trees.
</div>

### 📋 Problem

Imagine standing to the right of a tree and looking left.
Return the values of the nodes you can see (one per level).

```
Input:  [1, 2, 3, null, 5, null, 4]
Output: [1, 3, 4]

    1         ← see 1
   / \\
  2   3       ← see 3 (rightmost)
   \\   \\
    5   4     ← see 4 (rightmost)
```

**Constraints:** 0 ≤ nodes ≤ 100 | -100 ≤ Node.val ≤ 100
'''),

md('cell-mental-models', '''\
### 🧠 Choose Your Mental Model

| Model | The "Story" | Mechanism |
|-------|-------------|-----------|
| **Building from the Right** | "I\'m standing at the right end of the building. On each floor, the rightmost office\'s window is the only one I can see." | BFS: take `level[-1]` (last per level) |
| **Right-First Explorer** | "I always go right before left. The FIRST node I see at any depth is the rightmost one at that depth — nothing to its right was visited yet." | DFS right-first: `depth == len(result)` → append |
| **Obstructed View** | "A node is hidden if there\'s another node at the same depth to its right — it\'s blocked from view." | Equivalent to: rightmost node at each depth |
'''),

code('cell-brute-code', '''\
''' + TREENODE_CODE + '''
def rightSideView_brute(root: TreeNode) -> list[int]:
    """
    Collect full level order, take last element of each level.
    Time: O(n)  |  Space: O(n)
    Correct but builds unnecessary intermediate structure (all levels).
    """
    if not root:
        return []

    from collections import deque
    result = []
    queue = deque([root])

    while queue:
        level_size = len(queue)
        level = []
        for _ in range(level_size):
            node = queue.popleft()
            level.append(node.val)
            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)
        result.append(level[-1])   # only keep rightmost

    return result


# Test
root = build_tree([1, 2, 3, None, 5, None, 4])
print("Brute force:", rightSideView_brute(root))   # [1, 3, 4]
'''),

md('cell-complexity', '''\
## 🔬 Complexity Analysis

<div style="padding: 15px; border-left: 8px solid #1a8a5a; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>The Core Insight:</strong> Both BFS and DFS are O(n) time.
    The tradeoff is space: BFS is O(w) (max level width), DFS is O(h) (tree height).
    For a balanced tree: O(n) vs O(log n) — DFS wins on space.
    For a skewed tree: O(1) vs O(n) — BFS wins on space.
</div>

---

### The DFS Right-Side-View Insight

When traversing right-first DFS:
- The FIRST time we reach depth d, it\'s the rightmost node at that depth
- "First time at depth d" = `depth == len(result)` (result has entries 0..d-1)

```
depth=0: result=[], append 1  → result=[1]
depth=1: result=[1], we go RIGHT first → reach 3 first → append 3 → result=[1,3]
depth=1: then go left → reach 2, but depth 1 already in result → skip
depth=2: result=[1,3], right subtree of 3 has 4 → append 4 → result=[1,3,4]
depth=2: right subtree of 2 has 5 → but depth 2 already in result → skip
```

| Approach | Time | Space | Notes |
|----------|------|-------|-------|
| BFS full level order → take last | O(n) | O(w) | Builds all levels |
| **BFS — capture on last node** | **O(n)** | **O(w)** | Optimal BFS |
| DFS right-first | O(n) | O(h) | Better space for balanced trees |

<div style="padding: 10px; border-left: 8px solid #4CAF50; background-color: #f1f8f4; color: #1b5e20; border-radius: 4px;">
    <strong>✅ Default answer:</strong> BFS (more intuitive). Mention DFS right-first as the follow-up.
</div>
'''),

code('cell-optimal-code', '''\
from collections import deque

def rightSideView_bfs(root: TreeNode) -> list[int]:
    """
    BFS: capture the LAST node at each level.
    Time: O(n)  |  Space: O(w) — max level width
    The critical condition: i == level_size - 1 (last node at this level).
    """
    if not root:
        return []

    result = []
    queue = deque([root])

    while queue:
        level_size = len(queue)
        for i in range(level_size):
            node = queue.popleft()
            if i == level_size - 1:       # last node at this level — visible from right
                result.append(node.val)
            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)

    return result


def rightSideView_dfs(root: TreeNode) -> list[int]:
    """
    DFS right-first: first node seen at each depth is the rightmost.
    Time: O(n)  |  Space: O(h) — call stack depth
    More space-efficient for balanced trees.
    """
    result = []

    def dfs(node, depth):
        if not node:
            return
        if depth == len(result):         # first time at this depth = rightmost node
            result.append(node.val)
        dfs(node.right, depth + 1)       # ← RIGHT first (critical)
        dfs(node.left,  depth + 1)

    dfs(root, 0)
    return result


# Tests
root = build_tree([1, 2, 3, None, 5, None, 4])
print("BFS:", rightSideView_bfs(root))    # [1, 3, 4]
print("DFS:", rightSideView_dfs(root))    # [1, 3, 4]

# Left side view = same code, DFS LEFT-first OR BFS take first element per level
def leftSideView(root):
    result = []
    def dfs(node, depth):
        if not node: return
        if depth == len(result):
            result.append(node.val)
        dfs(node.left, depth + 1)    # LEFT first for left side view
        dfs(node.right, depth + 1)
    dfs(root, 0)
    return result

print("Left:", leftSideView(root))   # [1, 2, 5]
'''),

md('cell-qa', '''\
## 🎤 5 Interview Q&A

### Q1: In the DFS solution, why do we traverse right BEFORE left?

**Answer:** We want the FIRST node we see at each depth to be the rightmost one.
If we go right first, at any depth d, the first node we encounter is the one farthest to the right
(no unvisited nodes to its right). The condition `depth == len(result)` catches only
the first visit to each depth — so it captures the rightmost node.
If we went left first, we\'d get the left side view instead.

---

### Q2: How would you modify this to get the LEFT side view?

**Answer:** Two changes for DFS: traverse LEFT before right (swap the two recursive calls).
For BFS: take the FIRST element of each level instead of the last:
```python
if i == 0:           # first node = leftmost
    result.append(node.val)
```

---

### Q3: What is the space complexity of DFS vs BFS for a balanced tree of n nodes?

**Answer:**
- DFS: O(h) = O(log n) — call stack depth equals tree height
- BFS: O(w) = O(n) — worst case, the leaf level has n/2 nodes in the queue

So DFS is more space-efficient for balanced trees. For a skewed tree (all nodes to the right),
DFS space becomes O(n) while BFS stays O(1). The choice depends on expected tree shape.

---

### Q4: What if a node exists only on the left subtree — does the right side view capture it?

**Answer:** Yes, if it\'s the only node at its depth. Example: root with only a left child.
The left child IS the rightmost node at depth 1, so it appears in the right side view.
"Right side view" means the last node at each depth in BFS — if the only node at a depth
is on the left, it\'s still visible from the right.

---

### Q5: How does this relate to the problem of finding the "boundary" of a binary tree?

**Answer:** The right side view is the right boundary of the tree.
The full boundary = left boundary (top-down, left-first, no leaves) +
all leaves (left to right) + right boundary (bottom-up, right-first, no leaves).
The right side view is a simpler version: just the rightmost node at each level
including the root and all rightmost nodes, collected top-down.
'''),

md('cell-citi-narrative', '''\
## 💼 The Citi Narrative

**Context:** Citi\'s network topology was a tree: Core Switch → Distribution Switches → Access Switches → Servers.
The "right side view" of this tree represented the edge-most devices at each tier —
the servers and switches at the outermost boundary of the network.

**Practical Application:** Security team needed to identify all "edge-facing" devices —
those at the outermost position in each network tier. These required the strictest firewall rules.
The right side view algorithm identified exactly these devices: one per tier, the rightmost
(highest-index) device at each network depth.

**Extended Version:** Instead of just the rightmost value, the team needed all boundary devices
(left boundary + all leaves + right boundary). This maps to the "Binary Tree Boundary" problem —
but started with the right side view as the building block.

**Real data:** The network tree had:
- Depth 0: 1 core switch
- Depth 1: 8 distribution switches
- Depth 2: 64 access switches
- Depth 3: ~6,000 server ports

Right side view returned 4 values (one per depth). Security reviewed these 4 "most exposed"
devices as the starting point for network audit.

**Interview Line:** *"At Citi the network was a tree. The security audit started with
the \'rightmost device at each tier\' — that\'s the right side view. BFS, take last element
per level. 10 lines of code, then extend to full boundary traversal."*
'''),

code('cell-practice', '''\
# ── PRACTICE: Find the Largest Value in Each Tree Row (LC #515) ────────────
# Given the root of a binary tree, return the largest value in each row.
# Example: [1,3,2,5,3,null,9] → [1,3,9]
# Hint: same BFS skeleton, but instead of last value, track max value per level.

def largestValues(root: TreeNode) -> list[int]:
    # Your solution here
    pass

root = build_tree([1, 3, 2, 5, 3, None, 9])
print(largestValues(root))   # Expected: [1, 3, 9]

# Solution:
def largestValues_sol(root):
    if not root: return []
    from collections import deque
    result, queue = [], deque([root])
    while queue:
        level_size = len(queue)
        level_max = float('-inf')
        for _ in range(level_size):
            node = queue.popleft()
            level_max = max(level_max, node.val)
            if node.left:  queue.append(node.left)
            if node.right: queue.append(node.right)
        result.append(level_max)
    return result

print("Largest per row:", largestValues_sol(build_tree([1, 3, 2, 5, 3, None, 9])))  # [1,3,9]
'''),

md('cell-summary', '''\
## 🎯 Summary: Key Takeaways

### The Two Patterns

**BFS (intuitive):**
```python
if i == level_size - 1:    # last node at this level
    result.append(node.val)
```

**DFS right-first (space-efficient for balanced trees):**
```python
if depth == len(result):   # first time at this depth = rightmost
    result.append(node.val)
dfs(node.right, depth+1)   # RIGHT before LEFT
dfs(node.left,  depth+1)
```

### Variants Using the Same Skeleton
| Problem | Change |
|---------|--------|
| Right side view (this) | BFS last OR DFS right-first |
| Left side view | BFS first OR DFS left-first |
| Largest value per row | BFS: track max per level |
| Average per level | BFS: sum/count per level |
| Level order traversal | BFS: collect all per level |

### Interview Confidence Checklist
- [ ] Can write BFS solution from memory in 3 minutes
- [ ] Can write DFS right-first solution from memory
- [ ] Can explain why right-first DFS captures rightmost node
- [ ] Can extend to left side view (just swap left/right)
- [ ] Can name the Citi context: edge-facing network devices

**"Simplicity and clarity is Gold."** — Sean\'s Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/lc-0199-right-side-view.ipynb', LC199_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# Python — pytest and Testable Pipeline Code
# ─────────────────────────────────────────────────────────────────────────────

PYTEST_CELLS = [

md('c01', '''\
# Python — pytest: Writing Testable Pipeline Code
---

<div style="padding:15px;border-left:8px solid #1a8a5a;background:#e8f5e9;border-radius:4px;">
<strong>Core Insight:</strong> Untested pipelines fail silently in production.
The key pattern for data engineering: test pure transformation functions in isolation.
Don\'t test against live databases or S3 — mock external dependencies.
<code>pytest</code> is the standard. Fixtures avoid repetition. Parametrize catches edge cases.
</div>

### The Citi Context
At Citi, APM data collection pipelines ran nightly across 6,000 servers.
A bug in the CPU classification logic silently miscategorized "WARNING" servers as "OK"
for two weeks before anyone noticed. After adding pytest coverage with parametrized tests
for all threshold boundaries, that class of bug became impossible to ship.
'''),

code('c02', '''\
# ── 1. Basic pytest structure — functions, assertions, classes ───────────────
# Install: pip install pytest pandas
# Run: pytest test_transformations.py -v

# The functions we\'re testing (in transformations.py):

def compute_cpu_delta(today_cpu: float, yesterday_cpu: float) -> float:
    """Day-over-day CPU delta, rounded to 2 decimal places."""
    return round(today_cpu - yesterday_cpu, 2)


def classify_server(avg_cpu: float) -> str:
    """Classify server health based on average CPU utilization."""
    if avg_cpu >= 90:  return "CRITICAL"
    if avg_cpu >= 75:  return "WARNING"
    if avg_cpu >= 50:  return "NORMAL"
    return "IDLE"


# ── Tests: ────────────────────────────────────────────────────────────────────
import pytest

class TestCpuDelta:
    def test_positive_delta(self):
        assert compute_cpu_delta(80.5, 72.1) == 8.4

    def test_negative_delta(self):
        assert compute_cpu_delta(65.0, 72.5) == -7.5

    def test_zero_delta(self):
        assert compute_cpu_delta(72.5, 72.5) == 0.0

    def test_rounding(self):
        assert compute_cpu_delta(80.001, 70.002) == 9.999   # rounds correctly


class TestClassifyServer:
    # Parametrize: run the same test with multiple inputs — no copy-paste
    @pytest.mark.parametrize("cpu, expected", [
        (95.0,  "CRITICAL"),   # above threshold
        (90.0,  "CRITICAL"),   # exactly at threshold
        (89.9,  "WARNING"),    # just below CRITICAL
        (75.0,  "WARNING"),    # exactly at WARNING
        (74.9,  "NORMAL"),     # just below WARNING
        (50.0,  "NORMAL"),     # exactly at NORMAL
        (49.9,  "IDLE"),       # just below NORMAL
        (0.0,   "IDLE"),       # minimum
    ])
    def test_classification(self, cpu, expected):
        assert classify_server(cpu) == expected

# Run tests (simulated output — in real use, run pytest from terminal):
print("All threshold boundary tests pass if classify_server() is correct.")
print(classify_server(90.0), classify_server(89.9), classify_server(50.0))
'''),

code('c03', '''\
# ── 2. Fixtures — shared test data and setup ─────────────────────────────────
import pytest
import pandas as pd

@pytest.fixture
def sample_metrics_df():
    """
    Reusable DataFrame fixture — injected by pytest into any test that names it.
    Created ONCE per test (scope="function" by default).
    For expensive fixtures (SparkSession): scope="session" creates once per test run.
    """
    return pd.DataFrame({
        "server_id":   ["srv-01", "srv-02", "srv-03", "srv-04"],
        "avg_cpu":     [85.0,      45.2,     92.1,     75.0],
        "region":      ["us-east", "us-east", "eu-west", "eu-west"],
        "report_date": ["2026-02-26"] * 4
    })


def test_high_cpu_filter(sample_metrics_df):
    high_cpu = sample_metrics_df[sample_metrics_df["avg_cpu"] >= 80]
    assert len(high_cpu) == 2
    assert set(high_cpu["server_id"]) == {"srv-01", "srv-03"}


def test_critical_servers(sample_metrics_df):
    critical = sample_metrics_df[sample_metrics_df["avg_cpu"] >= 90]
    assert len(critical) == 1
    assert critical["server_id"].iloc[0] == "srv-03"


def test_mean_cpu(sample_metrics_df):
    mean = sample_metrics_df["avg_cpu"].mean()
    assert abs(mean - 74.325) < 0.001   # floating point: compare with tolerance


def test_region_groupby(sample_metrics_df):
    grouped = sample_metrics_df.groupby("region")["avg_cpu"].mean()
    assert abs(grouped["us-east"] - 65.1) < 0.01
    assert abs(grouped["eu-west"] - 83.55) < 0.01

# Simulate fixture usage (real use: just run `pytest`)
df = sample_metrics_df()   # call directly for demonstration
print(df)
print("High CPU servers:", df[df["avg_cpu"] >= 80]["server_id"].tolist())
'''),

code('c04', '''\
# ── 3. Mocking external dependencies — S3, databases, APIs ──────────────────
from unittest.mock import patch, MagicMock
import io, pandas as pd

# The function that calls S3 (we do NOT want actual S3 in tests)
def load_metrics_from_s3(bucket: str, key: str) -> pd.DataFrame:
    import boto3
    s3 = boto3.client("s3")
    obj = s3.get_object(Bucket=bucket, Key=key)
    return pd.read_csv(obj["Body"])


# ── Test it without touching S3 ───────────────────────────────────────────────
@patch("boto3.client")
def test_load_metrics_from_s3(mock_boto3):
    # Build mock response: fake CSV content as bytes
    csv_content = b"server_id,avg_cpu,report_date\nsrv-01,72.5,2026-02-26\nsrv-02,45.2,2026-02-26"

    mock_s3 = MagicMock()
    mock_boto3.return_value = mock_s3
    mock_s3.get_object.return_value = {"Body": io.BytesIO(csv_content)}

    # Call the real function — it uses the mocked boto3
    result = load_metrics_from_s3("my-bucket", "metrics/daily.csv")

    # Assert on result
    assert len(result) == 2
    assert result["avg_cpu"].iloc[0] == 72.5
    assert list(result.columns) == ["server_id", "avg_cpu", "report_date"]

    # Assert the mock was called correctly
    mock_s3.get_object.assert_called_once_with(Bucket="my-bucket", Key="metrics/daily.csv")

# Run the mock test directly (pytest would do this automatically)
test_load_metrics_from_s3()
print("Mock test passed — S3 was never called.")
'''),

code('c05', '''\
# ── 4. Testing pipeline transformations — pure functions are the sweet spot ──
import pandas as pd

# ❌ Anti-pattern: testing too much at once (integration test disguised as unit test)
# def test_full_pipeline():
#     run_pipeline()   # hits DB, S3, Spark — slow, fragile, not a unit test

# ✅ Pattern: decompose pipeline into pure transformation functions, test each

def filter_production_servers(df: pd.DataFrame) -> pd.DataFrame:
    """Keep only production environment servers."""
    return df[df["environment"] == "prod"].copy()


def add_alert_column(df: pd.DataFrame) -> pd.DataFrame:
    """Add alert_level column based on avg_cpu thresholds."""
    def classify(cpu):
        if cpu >= 90: return "CRITICAL"
        if cpu >= 75: return "WARNING"
        return "OK"
    df = df.copy()
    df["alert_level"] = df["avg_cpu"].apply(classify)
    return df


def aggregate_by_region(df: pd.DataFrame) -> pd.DataFrame:
    """Compute avg and max CPU per region."""
    return (df.groupby("region")
              .agg(avg_cpu=("avg_cpu", "mean"),
                   max_cpu=("avg_cpu", "max"),
                   server_count=("server_id", "count"))
              .reset_index())


# ── Unit tests for each pure function ─────────────────────────────────────────
def test_filter_production_servers():
    df = pd.DataFrame({
        "server_id": ["s1", "s2", "s3"],
        "environment": ["prod", "dev", "prod"],
        "avg_cpu": [80.0, 30.0, 90.0]
    })
    result = filter_production_servers(df)
    assert len(result) == 2
    assert set(result["server_id"]) == {"s1", "s3"}
    assert all(result["environment"] == "prod")


def test_add_alert_column_boundaries():
    df = pd.DataFrame({"avg_cpu": [95.0, 90.0, 89.9, 75.0, 74.9, 0.0], "server_id": list("abcdef")})
    result = add_alert_column(df)
    expected = ["CRITICAL", "CRITICAL", "WARNING", "WARNING", "OK", "OK"]
    assert list(result["alert_level"]) == expected


def test_aggregate_by_region():
    df = pd.DataFrame({
        "server_id": ["s1", "s2", "s3"],
        "region": ["east", "east", "west"],
        "avg_cpu": [70.0, 80.0, 90.0]
    })
    result = aggregate_by_region(df)
    east = result[result["region"] == "east"].iloc[0]
    assert abs(east["avg_cpu"] - 75.0) < 0.01
    assert east["max_cpu"] == 80.0
    assert east["server_count"] == 2


# Run all tests
test_filter_production_servers()
test_add_alert_column_boundaries()
test_aggregate_by_region()
print("All pipeline transformation tests passed.")
'''),

md('c06', '''\
## 🎤 5 Interview Q&A

**Q1: What is the difference between unit tests and integration tests?**

Unit tests test ONE function in isolation, with all dependencies mocked or stubbed.
They run in milliseconds and catch logic bugs.
Integration tests test multiple components working together with real (or near-real) external systems.
They catch wiring bugs — two components that work individually but break when combined.
In data engineering: unit test your transformation functions (pure, no I/O).
Integration test your end-to-end pipeline with a test database or local filesystem.

---

**Q2: What is `@pytest.fixture` and why use it instead of class setUp?**

A fixture is a factory that creates shared test resources and handles teardown automatically.
Unlike `setUp`, fixtures are injected by name — a test only gets the fixtures it names in its parameters.
This avoids creating expensive resources (SparkSession, DB connection) for tests that don\'t need them.
`scope="session"` creates the resource once for the entire test run — critical for SparkSession startup cost.

---

**Q3: When should you mock vs when should you test against the real thing?**

Mock when: the dependency is external (S3, database, API), slow, or has side effects.
Test against real when: you\'re writing an integration test and the real behavior matters.
Rule: unit tests should NEVER make network calls or write to disk.
Mock at the boundary where your code calls external code — use `@patch("boto3.client")`,
not a fake S3 service.

---

**Q4: What is `@pytest.mark.parametrize` and when is it essential?**

Parametrize runs the same test with multiple input/expected pairs, defined as a list of tuples.
Essential when: testing threshold boundaries (cpu=89.9 → WARNING, cpu=90.0 → CRITICAL).
Without it: you either write 8 identical test functions, or test only one case and miss boundaries.
Boundary testing is where most bugs hide — parametrize makes it painless to be thorough.

---

**Q5: How do you test a Spark job without running a full cluster?**

Use a local SparkSession in tests: `SparkSession.builder.master("local[1]").getOrCreate()`.
Test transformation functions with small DataFrames (10-100 rows).
Keep Spark tests in a separate test suite — they take 5-10 seconds to start.
Use `scope="session"` fixture so SparkSession starts once per test run, not once per test.
```python
@pytest.fixture(scope="session")
def spark():
    return SparkSession.builder.master("local[1]").appName("test").getOrCreate()
```
'''),

md('c07', '''\
## 📚 Key Terms

| Term | Definition |
|------|------------|
| **Unit Test** | Tests one function in isolation — no external calls, all dependencies mocked |
| **Integration Test** | Tests multiple components together with real (or near-real) external systems |
| **Fixture** | pytest factory that creates shared test resources and handles teardown |
| **Parametrize** | Run the same test with multiple inputs — `@pytest.mark.parametrize` |
| **Mock** | A fake object that replaces a dependency in tests — `unittest.mock.MagicMock` |
| **Patch** | Temporarily replace a module attribute during a test — `@patch("module.attribute")` |
| **Assertion** | A statement that must be true — `assert result == expected` |
| **Test Scope** | How long a fixture lives: function (default), class, module, session |
| **Pure Function** | No side effects, same output for same input — the ideal unit for testing |
| **Test Coverage** | % of code lines executed during test run — aim for >80% on core logic |
| **Boundary Test** | Testing at exact threshold values — where off-by-one errors hide |
| **Test Suite** | A collection of tests — often split into unit and integration suites |
'''),

md('c08', '''\
## 💼 The Citi Narrative

**Context:** The Citi APM pipeline classified servers into CRITICAL/WARNING/NORMAL/IDLE based
on average CPU. This classification drove automated Jira ticket creation for capacity review.

**The Bug:** For two weeks, servers at exactly 75.0% CPU were classified as "NORMAL" instead
of "WARNING" — a one-character bug (`>` instead of `>=`). No tests existed.
12 servers that needed capacity review were silently dropped from the Jira queue.

**The Fix — Adding pytest:**
1. Wrote parametrized tests for all 8 threshold boundary values
2. The bug was caught immediately on the first test run
3. Added fixtures for the standard test DataFrame (3 servers, one per tier)
4. Added mock tests for the S3 loader — tests now ran in 0.2 seconds instead of 30 seconds (no S3 calls)

**The Outcome:** After adding pytest coverage, zero classification bugs shipped in the next 6 months.
Test suite ran in CI in < 10 seconds. Every PR required green tests before merge.

**The Lesson:** The most common data pipeline bugs are boundary bugs in classification logic.
Parametrized tests at threshold values (exactly at, just below, just above) catch them
before they reach production.

**Interview Line:** *"At Citi we had a silent bug in CPU classification — servers at exactly 75%
weren\'t getting WARNING tickets. Two weeks, no one noticed. After adding parametrized pytest tests
for every threshold boundary, that class of bug became impossible to ship. Test run: 0.2 seconds.
Bug detection: immediate."*
'''),
]

write_nb(f'{BASE}/python-pytest.ipynb', PYTEST_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# SQL — CASE WHEN, Conditional Aggregation, and PIVOT
# ─────────────────────────────────────────────────────────────────────────────

SQL_CELLS = [

md('c01', '''\
# SQL — CASE WHEN, Conditional Aggregation, and PIVOT
---

<div style="padding:15px;border-left:8px solid #1a8a5a;background:#e8f5e9;border-radius:4px;">
<strong>Core Insight:</strong> Most databases don\'t have a native PIVOT keyword.
You build PIVOT with <code>CASE WHEN</code> inside aggregate functions — the
"conditional aggregation" pattern. It\'s universal, readable, and works everywhere:
DuckDB, PostgreSQL, Snowflake, BigQuery, Redshift.
</div>

### The Citi Context
Monthly capacity reports showed avg CPU per server as rows. The business team wanted
a wide-format table: one row per region, columns for each environment (dev, staging, prod).
That\'s a PIVOT. Built it with CASE WHEN — universally compatible, zero platform lock-in.
'''),

code('c02', '''\
# ── Setup: create tables in DuckDB ───────────────────────────────────────────
import duckdb
con = duckdb.connect()

con.execute("""
CREATE TABLE servers AS
SELECT * FROM (VALUES
  (\'SRV-001\', \'us-east\', \'prod\',    \'gold\'),
  (\'SRV-002\', \'us-east\', \'staging\', \'silver\'),
  (\'SRV-003\', \'us-east\', \'dev\',     \'bronze\'),
  (\'SRV-004\', \'eu-west\', \'prod\',    \'gold\'),
  (\'SRV-005\', \'eu-west\', \'prod\',    \'gold\'),
  (\'SRV-006\', \'eu-west\', \'dev\',     \'bronze\'),
  (\'SRV-007\', \'ap-south\',\'prod\',   \'gold\'),
  (\'SRV-008\', \'ap-south\',\'staging\',\'silver\')
) t(server_id, region, environment, tier)
""")

con.execute("""
CREATE TABLE daily_metrics AS
SELECT * FROM (VALUES
  (\'SRV-001\', DATE \'2026-02-26\', 85.2,  72.1),
  (\'SRV-001\', DATE \'2026-02-25\', 78.5,  68.3),
  (\'SRV-002\', DATE \'2026-02-26\', 45.0,  55.0),
  (\'SRV-003\', DATE \'2026-02-26\', 30.1,  40.2),
  (\'SRV-004\', DATE \'2026-02-26\', 91.3,  88.5),
  (\'SRV-005\', DATE \'2026-02-26\', 76.4,  80.1),
  (\'SRV-006\', DATE \'2026-02-26\', 22.0,  30.0),
  (\'SRV-007\', DATE \'2026-02-26\', 95.1,  92.3),
  (\'SRV-008\', DATE \'2026-02-26\', 55.0,  60.0)
) t(server_id, report_date, avg_cpu, avg_memory)
""")

print(con.execute("SELECT * FROM servers").df())
'''),

code('c03', '''\
# ── 1. PIVOT Pattern — rows to columns with CASE WHEN ────────────────────────
# Goal: one row per region, with avg CPU broken out by environment

result = con.execute("""
SELECT
    s.region,
    ROUND(AVG(CASE WHEN s.environment = \'prod\'    THEN m.avg_cpu END), 1) AS prod_avg_cpu,
    ROUND(AVG(CASE WHEN s.environment = \'staging\' THEN m.avg_cpu END), 1) AS staging_avg_cpu,
    ROUND(AVG(CASE WHEN s.environment = \'dev\'     THEN m.avg_cpu END), 1) AS dev_avg_cpu,
    COUNT(*) AS total_servers
FROM servers s
JOIN daily_metrics m ON s.server_id = m.server_id
WHERE m.report_date = \'2026-02-26\'
GROUP BY s.region
ORDER BY s.region
""").df()
print("PIVOT (CASE WHEN):")
print(result.to_string())
print()

# Why AVG() not SUM()? After the CASE WHEN filter, only one non-NULL value
# per environment per group row — AVG and MAX both work equally.
# Use SUM for counts: SUM(CASE WHEN env=\'prod\' THEN 1 ELSE 0 END)
print("Key rule: CASE WHEN inside AVG() = conditional average. Inside SUM() = conditional count.")
'''),

code('c04', '''\
# ── 2. Tier Distribution — COUNT and PCT with CASE WHEN ──────────────────────
result = con.execute("""
SELECT
    region,
    COUNT(*) AS total_servers,
    SUM(CASE WHEN tier = \'gold\'   THEN 1 ELSE 0 END) AS gold_count,
    SUM(CASE WHEN tier = \'silver\' THEN 1 ELSE 0 END) AS silver_count,
    SUM(CASE WHEN tier = \'bronze\' THEN 1 ELSE 0 END) AS bronze_count,
    ROUND(100.0 * SUM(CASE WHEN tier = \'gold\' THEN 1 ELSE 0 END) / COUNT(*), 1) AS pct_gold
FROM servers
GROUP BY region
ORDER BY total_servers DESC
""").df()
print("Tier distribution by region:")
print(result.to_string())
print()

# Alternative: FILTER clause (DuckDB / PostgreSQL — cleaner syntax)
result2 = con.execute("""
SELECT
    region,
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE tier = \'gold\')   AS gold_count,
    COUNT(*) FILTER (WHERE tier = \'silver\') AS silver_count,
    COUNT(*) FILTER (WHERE tier = \'bronze\') AS bronze_count
FROM servers
GROUP BY region
""").df()
print("Using FILTER clause (DuckDB/PostgreSQL equivalent):")
print(result2.to_string())
'''),

code('c05', '''\
# ── 3. UNPIVOT — columns to rows (reverse of PIVOT) ──────────────────────────
# Scenario: source data has avg_cpu and avg_memory as columns.
# We want: server_id, metric_type, value (long format for analysis)

result = con.execute("""
-- UNION ALL approach — works in every SQL engine
SELECT server_id, \'avg_cpu\'    AS metric_type, avg_cpu    AS value FROM daily_metrics
UNION ALL
SELECT server_id, \'avg_memory\' AS metric_type, avg_memory AS value FROM daily_metrics
ORDER BY server_id, metric_type
""").df()
print("UNPIVOT (wide → long format):")
print(result.head(10).to_string())
print()

# DuckDB also supports UNPIVOT syntax natively:
result2 = con.execute("""
UNPIVOT daily_metrics
ON avg_cpu, avg_memory
INTO NAME metric_type VALUE value
ORDER BY server_id
""").df()
print("Native UNPIVOT syntax (DuckDB):")
print(result2.head(8).to_string())
'''),

code('c06', '''\
# ── 4. Cohort Analysis Pattern ────────────────────────────────────────────────
# Group servers by first-seen date (cohort).
# Track which cohorts are still reporting data on day N after first seen.

result = con.execute("""
WITH first_report AS (
    -- Each server\'s cohort = the first date we saw it
    SELECT server_id, MIN(report_date) AS cohort_date
    FROM daily_metrics
    GROUP BY server_id
),
cohort_activity AS (
    SELECT
        m.server_id,
        f.cohort_date,
        m.report_date,
        (m.report_date - f.cohort_date)::INTEGER AS days_since_first
    FROM daily_metrics m
    JOIN first_report f ON m.server_id = f.server_id
)
-- PIVOT: one column per retention day
SELECT
    cohort_date,
    COUNT(DISTINCT server_id)                                          AS cohort_size,
    COUNT(DISTINCT CASE WHEN days_since_first = 0 THEN server_id END) AS day_0,
    COUNT(DISTINCT CASE WHEN days_since_first = 1 THEN server_id END) AS day_1
FROM cohort_activity
GROUP BY cohort_date
ORDER BY cohort_date
""").df()
print("Cohort analysis (retention by first-seen date):")
print(result.to_string())
'''),

md('c07', '''\
## 🎤 5 Interview Q&A

**Q1: Does DuckDB have a native PIVOT keyword?**

Yes — DuckDB has `PIVOT` syntax that auto-detects values. PostgreSQL requires CASE WHEN.
Snowflake has `PIVOT`. BigQuery recently added `PIVOT`. Redshift does not.
**Always learn the CASE WHEN approach first** — it\'s universal and you can use it on any platform.
The CASE WHEN approach is also more readable: the column names document exactly what each value means.

---

**Q2: When would you use `FILTER (WHERE ...)` instead of `CASE WHEN`?**

`FILTER` is cleaner syntax for conditional aggregation in PostgreSQL and DuckDB:
```sql
COUNT(*) FILTER (WHERE tier = \'gold\')   -- DuckDB/PostgreSQL
SUM(CASE WHEN tier = \'gold\' THEN 1 ELSE 0 END)   -- Universal
```
Same result, different syntax. Use `FILTER` in DuckDB/PostgreSQL for readability.
Use `CASE WHEN` when you need cross-platform compatibility (Redshift, MySQL).

---

**Q3: What is the difference between PIVOT and UNPIVOT?**

PIVOT transforms rows → columns: multiple rows for a server become one row with multiple columns.
UNPIVOT does the reverse: multiple columns become multiple rows. Use UNPIVOT when:
- Source data is wide-format (one column per metric) but you need long-format for analysis
- You want to apply a window function over all metrics together
- You\'re loading into a fact table with a single `value` column

---

**Q4: What is a cohort analysis and how does CASE WHEN enable it?**

Cohort analysis groups entities by their first occurrence date, then tracks behavior over time.
CASE WHEN enables this by conditional pivoting: `COUNT(CASE WHEN days_since_first = 0 THEN id END)`.
Real use: track which batches of servers first appeared in which week, then see which cohorts
are still reporting data 7 and 30 days later. Drop in reporting = data collection issue.

---

**Q5: How would you pivot when you don\'t know the column values ahead of time (dynamic pivot)?**

Static pivot (what we\'ve been doing) requires knowing values upfront — hard-coded in CASE WHEN.
Dynamic pivot: first query the distinct values, then build the SQL string programmatically.
In Python: `pd.pivot_table()` or `df.pivot()`. In SQL: dynamic SQL via stored procedures.
For an interview: state both approaches, explain why static is preferred when values are known
(readable, no injection risk, faster), and dynamic is required when values are unknown at query time.
'''),

md('c08', '''\
## 📚 Key Terms

| Term | Definition |
|------|------------|
| **PIVOT** | Rotating rows into columns — group + conditional aggregation |
| **UNPIVOT** | Rotating columns into rows — UNION ALL or native UNPIVOT |
| **Conditional Aggregation** | Using CASE WHEN inside an aggregate (SUM/AVG/COUNT) |
| **FILTER clause** | PostgreSQL/DuckDB syntax for conditional aggregation — `COUNT(*) FILTER (WHERE ...)` |
| **Wide Format** | One row per entity, multiple attribute columns — good for BI display |
| **Long Format** | One row per entity+attribute pair — good for analysis, window functions |
| **Cohort Date** | The date an entity first appeared — used to group entities into cohorts |
| **Cohort Analysis** | Track behavior over time relative to cohort date |
| **Static PIVOT** | Column values known at query-write time — hard-coded in CASE WHEN |
| **Dynamic PIVOT** | Column values unknown — requires programmatic SQL generation |

## 🎯 Summary

### The Universal PIVOT Pattern
```sql
SELECT
    group_col,
    AVG(CASE WHEN category = \'A\' THEN value END) AS cat_A,
    AVG(CASE WHEN category = \'B\' THEN value END) AS cat_B
FROM table GROUP BY group_col;
```

### Interview Confidence Checklist
- [ ] Can write PIVOT with CASE WHEN from memory in 3 minutes
- [ ] Can explain the difference between PIVOT and UNPIVOT
- [ ] Can write cohort analysis query with CASE WHEN
- [ ] Can use FILTER clause in DuckDB/PostgreSQL
- [ ] Can name the Citi narrative: wide-format capacity report

**"Simplicity and clarity is Gold."** — Sean\'s Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/sql-case-when-pivot.ipynb', SQL_CELLS)


# ─────────────────────────────────────────────────────────────────────────────
# Technology — Apache Airflow
# ─────────────────────────────────────────────────────────────────────────────

AIRFLOW_CELLS = [

md('c01', '''\
# Technology — Apache Airflow: Pipeline Orchestration
---

<div style="padding:15px;border-left:8px solid #1a8a5a;background:#e8f5e9;border-radius:4px;">
<strong>Core Insight:</strong> Airflow is the de facto standard for data pipeline orchestration.
You describe pipelines as DAGs in Python code — you get version control, testing, and code reuse.
Two rules prevent 90% of Airflow disasters: <code>catchup=False</code> and idempotent tasks.
</div>

### The Citi Context
Citi\'s APM data pipeline ran nightly across 6,000 servers. Before Airflow:
shell scripts, cron jobs, no retry logic, no monitoring, silent failures.
After Airflow: DAG with retries, XCom for row count validation, email alerting,
and idempotent S3 writes. Mean-time-to-detect pipeline failures dropped from 6 hours to 90 seconds.

### Core Concepts

```
DAG (Directed Acyclic Graph)
├── Task 1: Extract metrics (PythonOperator)
│   └── Task 2: Validate row count (PythonOperator)   ← depends on Task 1
│       ├── Task 3a: Load to S3 (S3Hook)              ← depends on Task 2
│       └── Task 3b: Update catalog (GlueCrawler)     ← depends on Task 2
│           └── Task 4: Send alert (EmailOperator)    ← depends on Task 3b (on failure)
```

| Component | Role |
|-----------|------|
| **DAG** | Workflow definition — tasks + dependencies |
| **Task** | Unit of work — implemented as an Operator |
| **Operator** | Task type: PythonOperator, BashOperator, S3Hook, GlueCrawlerOperator |
| **Schedule** | Cron expression: `@daily` = `0 0 * * *` |
| **XCom** | Cross-task message passing (small values only — not DataFrames) |
| **Sensor** | Waits for external condition (S3FileExists, ExternalTask) |
'''),

code('c02', '''\
# ── A production-grade Airflow DAG ───────────────────────────────────────────
# Note: This code is illustrative — run it in an Airflow environment
# In this notebook, we show the structure and explain each decision

DAG_CODE = """
from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.operators.glue_crawler import GlueCrawlerOperator

# Default arguments inherited by ALL tasks in this DAG
default_args = {
    "owner":            "data-engineering",
    "retries":          3,
    "retry_delay":      timedelta(minutes=5),
    "email_on_failure": True,
    "email":            ["de-alerts@citi.com"],
    "depends_on_past":  False,     # don\'t wait for previous run to succeed
}

with DAG(
    dag_id          = "daily_server_metrics",
    schedule_interval = "0 6 * * *",        # 6 AM UTC daily
    start_date      = datetime(2026, 1, 1),
    catchup         = False,                 # ← CRITICAL: no backfilling on first deploy
    default_args    = default_args,
    tags            = ["capacity", "telemetry"],
    max_active_runs = 1,                     # prevent concurrent runs
) as dag:

    def extract_metrics(**context):
        ds = context["ds"]   # execution date: "2026-02-27"
        # Pull from APM API, write raw JSON to s3://citi-raw/apm/{ds}/
        # ...
        rows = 6124   # simulate: fetched 6,124 rows
        # Push to XCom so downstream tasks can validate
        context["task_instance"].xcom_push(key="row_count", value=rows)
        return {"rows": rows, "date": ds}

    def validate_metrics(**context):
        ti = context["task_instance"]
        upstream = ti.xcom_pull(task_ids="extract_metrics", key="row_count")
        if upstream < 5000:
            raise ValueError(f"Row count too low: {upstream} (expected >= 5000)")
        print(f"Validation passed: {upstream} rows")

    def transform_and_load(**context):
        ds = context["ds"]
        # Read from raw S3, transform, write Parquet to s3://citi-processed/apm/{ds}/
        # This is idempotent: overwrite the partition if it already exists
        pass

    extract  = PythonOperator(task_id="extract_metrics",   python_callable=extract_metrics)
    validate = PythonOperator(task_id="validate_metrics",  python_callable=validate_metrics)
    load     = PythonOperator(task_id="transform_and_load", python_callable=transform_and_load)
    crawl    = GlueCrawlerOperator(task_id="update_catalog",
                                   config={"Name": "server-metrics-crawler"})

    # Define dependencies with >> (bitshift)
    extract >> validate >> load >> crawl
"""

print(DAG_CODE)
print("\\n--- Key architectural decisions in this DAG: ---")
print("1. catchup=False: no backfilling on first deploy")
print("2. max_active_runs=1: prevents concurrent runs on same partition")
print("3. XCom for row count: validate before loading (fail fast)")
print("4. Idempotent load: overwrite S3 partition → safe to retry")
print("5. retries=3 with 5-min delay: handles transient API failures")
'''),

code('c03', '''\
# ── XCom: cross-task communication ───────────────────────────────────────────
# XCom = cross-communication. Tasks push small values, downstream tasks pull them.
# CRITICAL LIMITATION: XCom stores values in the Airflow metadata DB.
# Never push DataFrames, large lists, or file content via XCom.
# Push: row counts, file paths, status flags, small dicts.

XCOM_EXAMPLE = """
# Task 1: extract — pushes row count
def extract(**context):
    ti = context["task_instance"]
    rows = 6124
    ti.xcom_push(key="row_count", value=rows)
    ti.xcom_push(key="s3_path", value="s3://citi-raw/apm/2026-02-27/part-00001.json")

# Task 2: validate — pulls row count from Task 1
def validate(**context):
    ti = context["task_instance"]
    row_count = ti.xcom_pull(task_ids="extract", key="row_count")
    s3_path   = ti.xcom_pull(task_ids="extract", key="s3_path")
    assert row_count >= 5000, f"Too few rows: {row_count}"

# Task 3: load — uses S3 path from Task 1
def load(**context):
    ti = context["task_instance"]
    s3_path = ti.xcom_pull(task_ids="extract", key="s3_path")
    # read from s3_path, transform, write to processed/
"""

print(XCOM_EXAMPLE)
print("XCom rules:")
print("  ✅ Push: row_count (int), s3_path (str), status (bool), config (small dict)")
print("  ❌ Never push: DataFrames, Spark DataFrames, file contents, large lists")
print("  Why: XCom is stored in the Airflow metadata DB (PostgreSQL).")
print("  Large values = slow serialization + metadata DB bloat")
'''),

code('c04', '''\
# ── Idempotency: the most important Airflow principle ────────────────────────
# A DAG run is idempotent if re-running it produces the SAME result, not duplicate data.
# Required because: Airflow retries failed tasks automatically.
# If task fails after partially writing data, retry must produce clean output.

print("=== IDEMPOTENCY PATTERNS ===")
print()

# Pattern 1: S3 partition overwrite (Spark / PySpark)
SPARK_IDEMPOTENT = """
# ❌ Non-idempotent: appends on retry → duplicate data
df.write.mode("append").parquet("s3://bucket/date=2026-02-27/")

# ✅ Idempotent: overwrites partition on retry → same output
df.write.mode("overwrite").partitionBy("date").parquet("s3://bucket/")
"""
print("Pattern 1: Spark partition overwrite")
print(SPARK_IDEMPOTENT)

# Pattern 2: SQL DELETE then INSERT
SQL_IDEMPOTENT = """
-- ❌ Non-idempotent: INSERT on retry → duplicate rows
INSERT INTO daily_summary SELECT * FROM staging WHERE report_date = '2026-02-27';

-- ✅ Idempotent: DELETE then INSERT → same output on retry
DELETE FROM daily_summary WHERE report_date = '2026-02-27';
INSERT INTO daily_summary SELECT * FROM staging WHERE report_date = '2026-02-27';
"""
print("Pattern 2: DELETE + INSERT")
print(SQL_IDEMPOTENT)

# Pattern 3: ON CONFLICT (upsert)
SQL_UPSERT = """
-- ✅ Idempotent UPSERT: insert if new, update if exists
INSERT INTO daily_summary (server_id, report_date, avg_cpu)
SELECT server_id, report_date, avg_cpu FROM staging
ON CONFLICT (server_id, report_date) DO UPDATE SET avg_cpu = EXCLUDED.avg_cpu;
"""
print("Pattern 3: UPSERT (ON CONFLICT)")
print(SQL_UPSERT)
'''),

md('c05', '''\
## 🎤 5 Interview Q&A

**Q1: What is `catchup=False` and why do you almost always want it?**

Without `catchup=False`, Airflow backfills all DAG runs from `start_date` to today.
If you deploy a DAG with `start_date=2026-01-01` today (March), Airflow queues
~60 historical runs immediately — flooding your workers and potentially inserting
60 copies of data. `catchup=False` prevents this: only future scheduled runs execute.
Set `catchup=True` only when you explicitly want historical backfilling (e.g., loading
historical data for the first time). Otherwise: always `catchup=False`.

---

**Q2: What is an XCom and what is its most important limitation?**

XCom (cross-communication) passes small values between tasks via the Airflow metadata DB.
One task pushes: `ti.xcom_push(key="row_count", value=6124)`.
Another task pulls: `ti.xcom_pull(task_ids="extract", key="row_count")`.
**Critical limitation:** XCom is stored in the metadata DB (PostgreSQL/MySQL).
Never push DataFrames, file contents, or large lists — they serialize slowly and bloat the DB.
XCom is for metadata: row counts, S3 file paths, status flags, small config dicts.

---

**Q3: What happens when an Airflow task fails?**

It retries `retries` times (from `default_args`) with `retry_delay` between attempts.
After exhausting retries: task status = FAILED. Downstream tasks that depend on it
are marked `UPSTREAM_FAILED` and don\'t execute. Airflow sends email if `email_on_failure=True`.
The DAG run is marked FAILED. You can manually clear the failed task to retry it after fixing the root cause.

---

**Q4: How do you make an Airflow DAG idempotent?**

Idempotent = running the same DAG run multiple times produces the same result (no duplicates).
Three patterns: (1) Spark: `mode("overwrite")` on the date partition — retry overwrites, no duplicates.
(2) SQL: `DELETE FROM table WHERE date = ds; INSERT...` — delete before inserting.
(3) UPSERT: `INSERT ... ON CONFLICT DO UPDATE` — merge semantics.
The execution date `{{ ds }}` scopes every read and write — each run processes exactly its own date.

---

**Q5: What is the difference between `LocalExecutor`, `CeleryExecutor`, and `KubernetesExecutor`?**

`LocalExecutor`: runs tasks as subprocesses on the Airflow scheduler machine. Simple, no extra infra.
Good for: small teams, < 20 DAGs, single-machine setups.
`CeleryExecutor`: distributes tasks to a pool of worker machines via a message broker (Redis/RabbitMQ).
Good for: medium scale, predictable workloads, existing team Celery expertise.
`KubernetesExecutor`: runs each task in its own Kubernetes pod. Scales to zero when idle.
Good for: variable workloads, per-task resource customization, cloud-native environments.
At Citi scale: CeleryExecutor with 5 workers was sufficient for ~200 DAGs.
'''),

md('c06', '''\
## 📚 Key Terms

| Term | Definition |
|------|------------|
| **DAG** | Directed Acyclic Graph — the workflow definition. Contains tasks + dependencies. |
| **Task** | Unit of work inside a DAG — implemented as an Operator |
| **Operator** | Task type: PythonOperator, BashOperator, SparkSubmitOperator, etc. |
| **Schedule Interval** | Cron expression controlling when the DAG runs |
| **catchup=False** | Prevents backfilling missed DAG runs since start_date |
| **XCom** | Cross-task message passing — stored in metadata DB, small values only |
| **Sensor** | Task that waits for an external condition before proceeding |
| **Executor** | How Airflow runs tasks: Local, Celery, or Kubernetes |
| **Idempotency** | Re-running produces the same result — critical for safe retries |
| **Execution Date** | The logical date of a DAG run — `{{ ds }}` in Jinja templates |
| **Connection** | Stored credential (S3, Glue, Redshift) — reusable across DAGs |
| **Variable** | Key-value config store — accessible in any DAG |

## 🎯 Summary

### The Two Rules That Prevent 90% of Airflow Disasters
1. `catchup=False` — no unintended backfilling on deploy
2. Idempotent tasks — safe to retry without duplicate data

### Dependency Syntax
```python
extract >> validate >> load >> crawl    # linear
extract >> [validate_a, validate_b]     # fan-out
[validate_a, validate_b] >> load        # fan-in
```

### Interview Confidence Checklist
- [ ] Can explain what a DAG is and how tasks relate
- [ ] Can explain catchup=False and why it matters
- [ ] Can explain XCom limitation (never DataFrames)
- [ ] Can explain three idempotency patterns
- [ ] Can name the Citi narrative: 6h MTTD → 90s

**"Simplicity and clarity is Gold."** — Sean\'s Study Mantra 🚀
'''),
]

write_nb(f'{BASE}/airflow-orchestration.ipynb', AIRFLOW_CELLS)


print('\n=== Day 8 notebooks complete! ===')
print('Files written:')
for f in sorted(os.listdir(BASE)):
    print(f'  {f}')
print('\nNext: Update _gen_html.py to add Trees theme and Day 8 LC problems, then run it.')
